export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const AUTO_SIGN_IN = 'AUTO_SIGN_IN'

export const GET_CHATS = 'GET_CHATS'
export const GET_CHAT = 'GET_CHAT'
export const ADD_CHAT = 'ADD_CHAT'
export const DELETE_CHAT = 'DELETE_CHAT'
export const ADD_MESSAGE = 'ADD_MESSAGE'
